# Generated by Django 4.2.30 on 2026-09-22 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='停用开始日期')),
                ('end_date', models.DateField(help_text='停用结束日期')),
                ('reason', models.TextField(help_text='停用原因')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('applied', '已生效'), ('recovered', '已恢复')], default='pending', max_length=20)),
                ('disposal', models.CharField(blank=True, choices=[('relocate', '调整教室'), ('cancel', '停课')], help_text='确认时选择的处置方式：调整教室或停课', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='core.classroom')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_suspensions', to='core.semester')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(help_text='1-5 代表周一到周五')),
                ('period', models.IntegerField(help_text='第几节课')),
                ('is_locked', models.BooleanField(default=False, help_text='锁定后不参与自动重排')),
                ('is_conflict', models.BooleanField(default=False)),
                ('conflict_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.class')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('original_teacher', models.ForeignKey(blank=True, help_text='如果是代课，记录原教师', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_for', to='core.teacher')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'ordering': ['semester', 'day_of_week', 'period'],
            },
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_source', to='scheduling.scheduleentry')),
                ('entry2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_target', to='scheduling.scheduleentry')),
                ('requesting_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_made', to='core.teacher')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('target_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='core.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_record', to='scheduling.scheduleentry')),
                ('original_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='core.teacher')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='core.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('teacher', '教师冲突'), ('classroom', '教室冲突'), ('class', '班级冲突')], max_length=20)),
                ('day_of_week', models.IntegerField()),
                ('period', models.IntegerField()),
                ('involved_entries', models.JSONField(default=list)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomSuspensionDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('relocated', '已调整教室'), ('cancelled', '已停课')], max_length=20)),
                ('class_name', models.CharField(blank=True, max_length=100)),
                ('course_name', models.CharField(blank=True, max_length=100)),
                ('day_of_week', models.IntegerField(default=1)),
                ('period', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspension_dispositions', to='scheduling.scheduleentry')),
                ('new_classroom', models.ForeignKey(blank=True, help_text='停课记录该字段为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositions_as_new', to='core.classroom')),
                ('original_classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositions_as_original', to='core.classroom')),
                ('suspension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='scheduling.classroomsuspension')),
            ],
            options={
                'ordering': ['day_of_week', 'period'],
                'unique_together': {('suspension', 'entry')},
            },
        ),
        migrations.CreateModel(
            name='ClassCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='core.class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'ordering': ['semester', 'class_id'],
                'unique_together': {('class_id', 'course', 'teacher', 'semester')},
            },
        ),
    ]
